### ISSUE TITLE
Need to figure out how to import python modules between folders

### ISSUE THREAD

**Issue by aes88** [sameer0805/WebDatabase#6]
We've been working on main.py in a submodule (because that's how we imported it from Suyash's example on github) but now we need it to reference processing scripts that are in this general repository.. is there a way to reference these files from a python module? I haven't found a way that works - alternatively we could just move these files out of the submodule and into our WebDatabase folder, but I was assuming we should find a better workaround...

**Comment by mlp6** [comment]
Do you mind asking this here: https://gitter.im/Duke-BME-Hackers/Software  This would be a nice general question to get out there for the whole group to see.

**Comment by aes88** [comment]
we manually copied everything into this repository and have been modifying from here
