### ISSUE TITLE
foreseeing difficulty with travis: how do we get it to run unit tests that require the tensorflow container?

### ISSUE THREAD

**Issue by aes88** [sameer0805/WebDatabase#9]
I could only run the tests by logging into the web server docker container, and running the tests from there

**Comment by aes88** [comment]
Some additional background on this:
-I know our old travis method opened a virtual environment with requirements we specified
but in this case it would require the dependencies from tensorflow and i had no clue how to do that in anything besides docker
- so I tried to build the same docker container in the travis file.... but then when I ran py.test it would run on the virtual travis machine not in the container!
- I then tried to figure out how to remote into the docker web server database and successfully did that... but could not then run the command "py.test" so that was sad

**Comment by suyashkumar** [comment]
Nice progress, you're exactly right on the exec'ing into the Docker container. I was able to try:

`docker exec -it webdatabase_server_1 py.test test_melanoma.py`

This will go into the currently running container with the name webdatabase_server_1 and run the command "py.test test_melanoma.py" :) Give this a go!

**Comment by suyashkumar** [comment]
You can see the name of the currently running containers by doing `docker ps`, but the name should be the same in this case

**Comment by suyashkumar** [comment]
So the docker command I provided would just run on line 25 [here](https://github.com/sameer0805/WebDatabase/blob/frontend/.travis.yml#L24) :). And you wouldn't need the last line

**Comment by aes88** [comment]
thank you!!
